version: '3.7'
volumes:
  mariadb-data:
  drupal-files:
services:
  drupal:
    build: .
    labels:
      traefik.enable: "true"
      traefik.http.middlewares.drupal-redirectscheme.redirectscheme.permanent: "true"
      traefik.http.middlewares.drupal-redirectscheme.redirectscheme.scheme: https
      traefik.http.routers.drupal_http.service: drupal
      traefik.http.routers.drupal_http.entrypoints: http
      traefik.http.routers.drupal_http.middlewares: drupal-redirectscheme
      traefik.http.routers.drupal_http.rule: Host(`acu.traefik.me`)
      traefik.http.routers.drupal_https.service: drupal
      traefik.http.routers.drupal_https.entrypoints: https
      traefik.http.routers.drupal_https.rule: Host(`acu.traefik.me`)
      traefik.http.routers.drupal_https.tls: "true"
      traefik.http.services.drupal.loadbalancer.server.port: '80'
    environment:
      DRUPAL_DEFAULT_CONFIGDIR: /var/www/drupal/config/sync
      DRUPAL_DEFAULT_INSTALL_EXISTING_CONFIG: "false"
    volumes:
      - drupal-files:/var/www/drupal/web/sites/default:rw
  mariadb:
    image: local/mariadb:latest
    volumes:
      - mariadb-data:/var/lib/mysql:rw
  traefik:
    command: >
      --api.insecure=true
      --api.dashboard=true
      --api.debug=true
      --entryPoints.http.address=:80
      --entryPoints.https.address=:443
      --providers.docker
      --providers.docker.network=default
      --providers.docker.exposedByDefault=false
      '--providers.docker.defaultRule=Host(`{{index .Labels "com.docker.compose.service" }}.traefik.me`)'
    container_name: traefik
    image: traefik:2.2.1
    labels:
      traefik.http.routers.api.service: api@internal
    networks:
      default:
        aliases:
          - acu.traefik.me
    ports:
      - published: 80
        target: 80
      - published: 443
        target: 443
      - published: 8080
        target: 8080
    volumes:
      - ./certs:/etc/ssl/traefik:rw
      - ./tls.yml:/etc/traefik/tls.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock:rw